
  ## Try Catch
  
  try
  {
    # Code Here!
  }
  catch (ex)
  {
    # Code Here!
	ex.description
  }
  finally
  {
    # Code Here!
  }
  
  throw("My Error");